# Setup
title:               Bartosz Rybarski
tagline:             'Personal blog'
description:         ''
url:                 http://www.bartekryba.github.io
baseurl:             'https://www.github.com/bartekryba/bartekryba.github.io'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Bartosz Rybarski
  url:               https://twitter.com/bartekryba
  email:             bartoszrybarski@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
google_analytics_id: #UA-XXXX-Y
